# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vbroda/inventory-project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vbroda/inventory-project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vbroda/inventory-project/CMakeFiles /home/vbroda/inventory-project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vbroda/inventory-project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named gen-inventory

# Build rule for target.
gen-inventory: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gen-inventory
.PHONY : gen-inventory

# fast build rule for target.
gen-inventory/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-inventory.dir/build.make CMakeFiles/gen-inventory.dir/build
.PHONY : gen-inventory/fast

#=============================================================================
# Target rules for targets named gen-sales

# Build rule for target.
gen-sales: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gen-sales
.PHONY : gen-sales

# fast build rule for target.
gen-sales/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-sales.dir/build.make CMakeFiles/gen-sales.dir/build
.PHONY : gen-sales/fast

#=============================================================================
# Target rules for targets named main_autogen

# Build rule for target.
main_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main_autogen
.PHONY : main_autogen

# fast build rule for target.
main_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_autogen.dir/build.make CMakeFiles/main_autogen.dir/build
.PHONY : main_autogen/fast

#=============================================================================
# Target rules for targets named gen-inventory_autogen

# Build rule for target.
gen-inventory_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gen-inventory_autogen
.PHONY : gen-inventory_autogen

# fast build rule for target.
gen-inventory_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-inventory_autogen.dir/build.make CMakeFiles/gen-inventory_autogen.dir/build
.PHONY : gen-inventory_autogen/fast

#=============================================================================
# Target rules for targets named gen-sales_autogen

# Build rule for target.
gen-sales_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gen-sales_autogen
.PHONY : gen-sales_autogen

# fast build rule for target.
gen-sales_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-sales_autogen.dir/build.make CMakeFiles/gen-sales_autogen.dir/build
.PHONY : gen-sales_autogen/fast

gen-inventory_autogen/mocs_compilation.o: gen-inventory_autogen/mocs_compilation.cpp.o
.PHONY : gen-inventory_autogen/mocs_compilation.o

# target to build an object file
gen-inventory_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-inventory.dir/build.make CMakeFiles/gen-inventory.dir/gen-inventory_autogen/mocs_compilation.cpp.o
.PHONY : gen-inventory_autogen/mocs_compilation.cpp.o

gen-inventory_autogen/mocs_compilation.i: gen-inventory_autogen/mocs_compilation.cpp.i
.PHONY : gen-inventory_autogen/mocs_compilation.i

# target to preprocess a source file
gen-inventory_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-inventory.dir/build.make CMakeFiles/gen-inventory.dir/gen-inventory_autogen/mocs_compilation.cpp.i
.PHONY : gen-inventory_autogen/mocs_compilation.cpp.i

gen-inventory_autogen/mocs_compilation.s: gen-inventory_autogen/mocs_compilation.cpp.s
.PHONY : gen-inventory_autogen/mocs_compilation.s

# target to generate assembly for a file
gen-inventory_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-inventory.dir/build.make CMakeFiles/gen-inventory.dir/gen-inventory_autogen/mocs_compilation.cpp.s
.PHONY : gen-inventory_autogen/mocs_compilation.cpp.s

gen-sales_autogen/mocs_compilation.o: gen-sales_autogen/mocs_compilation.cpp.o
.PHONY : gen-sales_autogen/mocs_compilation.o

# target to build an object file
gen-sales_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-sales.dir/build.make CMakeFiles/gen-sales.dir/gen-sales_autogen/mocs_compilation.cpp.o
.PHONY : gen-sales_autogen/mocs_compilation.cpp.o

gen-sales_autogen/mocs_compilation.i: gen-sales_autogen/mocs_compilation.cpp.i
.PHONY : gen-sales_autogen/mocs_compilation.i

# target to preprocess a source file
gen-sales_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-sales.dir/build.make CMakeFiles/gen-sales.dir/gen-sales_autogen/mocs_compilation.cpp.i
.PHONY : gen-sales_autogen/mocs_compilation.cpp.i

gen-sales_autogen/mocs_compilation.s: gen-sales_autogen/mocs_compilation.cpp.s
.PHONY : gen-sales_autogen/mocs_compilation.s

# target to generate assembly for a file
gen-sales_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-sales.dir/build.make CMakeFiles/gen-sales.dir/gen-sales_autogen/mocs_compilation.cpp.s
.PHONY : gen-sales_autogen/mocs_compilation.cpp.s

main_autogen/mocs_compilation.o: main_autogen/mocs_compilation.cpp.o
.PHONY : main_autogen/mocs_compilation.o

# target to build an object file
main_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main_autogen/mocs_compilation.cpp.o
.PHONY : main_autogen/mocs_compilation.cpp.o

main_autogen/mocs_compilation.i: main_autogen/mocs_compilation.cpp.i
.PHONY : main_autogen/mocs_compilation.i

# target to preprocess a source file
main_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main_autogen/mocs_compilation.cpp.i
.PHONY : main_autogen/mocs_compilation.cpp.i

main_autogen/mocs_compilation.s: main_autogen/mocs_compilation.cpp.s
.PHONY : main_autogen/mocs_compilation.s

# target to generate assembly for a file
main_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main_autogen/mocs_compilation.cpp.s
.PHONY : main_autogen/mocs_compilation.cpp.s

src/ActiveInventory.o: src/ActiveInventory.cpp.o
.PHONY : src/ActiveInventory.o

# target to build an object file
src/ActiveInventory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ActiveInventory.cpp.o
.PHONY : src/ActiveInventory.cpp.o

src/ActiveInventory.i: src/ActiveInventory.cpp.i
.PHONY : src/ActiveInventory.i

# target to preprocess a source file
src/ActiveInventory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ActiveInventory.cpp.i
.PHONY : src/ActiveInventory.cpp.i

src/ActiveInventory.s: src/ActiveInventory.cpp.s
.PHONY : src/ActiveInventory.s

# target to generate assembly for a file
src/ActiveInventory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ActiveInventory.cpp.s
.PHONY : src/ActiveInventory.cpp.s

src/CSVEntry.o: src/CSVEntry.cpp.o
.PHONY : src/CSVEntry.o

# target to build an object file
src/CSVEntry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-inventory.dir/build.make CMakeFiles/gen-inventory.dir/src/CSVEntry.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-sales.dir/build.make CMakeFiles/gen-sales.dir/src/CSVEntry.cpp.o
.PHONY : src/CSVEntry.cpp.o

src/CSVEntry.i: src/CSVEntry.cpp.i
.PHONY : src/CSVEntry.i

# target to preprocess a source file
src/CSVEntry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-inventory.dir/build.make CMakeFiles/gen-inventory.dir/src/CSVEntry.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-sales.dir/build.make CMakeFiles/gen-sales.dir/src/CSVEntry.cpp.i
.PHONY : src/CSVEntry.cpp.i

src/CSVEntry.s: src/CSVEntry.cpp.s
.PHONY : src/CSVEntry.s

# target to generate assembly for a file
src/CSVEntry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-inventory.dir/build.make CMakeFiles/gen-inventory.dir/src/CSVEntry.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-sales.dir/build.make CMakeFiles/gen-sales.dir/src/CSVEntry.cpp.s
.PHONY : src/CSVEntry.cpp.s

src/Date.o: src/Date.cpp.o
.PHONY : src/Date.o

# target to build an object file
src/Date.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-sales.dir/build.make CMakeFiles/gen-sales.dir/src/Date.cpp.o
.PHONY : src/Date.cpp.o

src/Date.i: src/Date.cpp.i
.PHONY : src/Date.i

# target to preprocess a source file
src/Date.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-sales.dir/build.make CMakeFiles/gen-sales.dir/src/Date.cpp.i
.PHONY : src/Date.cpp.i

src/Date.s: src/Date.cpp.s
.PHONY : src/Date.s

# target to generate assembly for a file
src/Date.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-sales.dir/build.make CMakeFiles/gen-sales.dir/src/Date.cpp.s
.PHONY : src/Date.cpp.s

src/HelperFunctions.o: src/HelperFunctions.cpp.o
.PHONY : src/HelperFunctions.o

# target to build an object file
src/HelperFunctions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/HelperFunctions.cpp.o
.PHONY : src/HelperFunctions.cpp.o

src/HelperFunctions.i: src/HelperFunctions.cpp.i
.PHONY : src/HelperFunctions.i

# target to preprocess a source file
src/HelperFunctions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/HelperFunctions.cpp.i
.PHONY : src/HelperFunctions.cpp.i

src/HelperFunctions.s: src/HelperFunctions.cpp.s
.PHONY : src/HelperFunctions.s

# target to generate assembly for a file
src/HelperFunctions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/HelperFunctions.cpp.s
.PHONY : src/HelperFunctions.cpp.s

src/InventoryGenerator.o: src/InventoryGenerator.cpp.o
.PHONY : src/InventoryGenerator.o

# target to build an object file
src/InventoryGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-inventory.dir/build.make CMakeFiles/gen-inventory.dir/src/InventoryGenerator.cpp.o
.PHONY : src/InventoryGenerator.cpp.o

src/InventoryGenerator.i: src/InventoryGenerator.cpp.i
.PHONY : src/InventoryGenerator.i

# target to preprocess a source file
src/InventoryGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-inventory.dir/build.make CMakeFiles/gen-inventory.dir/src/InventoryGenerator.cpp.i
.PHONY : src/InventoryGenerator.cpp.i

src/InventoryGenerator.s: src/InventoryGenerator.cpp.s
.PHONY : src/InventoryGenerator.s

# target to generate assembly for a file
src/InventoryGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-inventory.dir/build.make CMakeFiles/gen-inventory.dir/src/InventoryGenerator.cpp.s
.PHONY : src/InventoryGenerator.cpp.s

src/InventoryGeneratorDriver.o: src/InventoryGeneratorDriver.cpp.o
.PHONY : src/InventoryGeneratorDriver.o

# target to build an object file
src/InventoryGeneratorDriver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-inventory.dir/build.make CMakeFiles/gen-inventory.dir/src/InventoryGeneratorDriver.cpp.o
.PHONY : src/InventoryGeneratorDriver.cpp.o

src/InventoryGeneratorDriver.i: src/InventoryGeneratorDriver.cpp.i
.PHONY : src/InventoryGeneratorDriver.i

# target to preprocess a source file
src/InventoryGeneratorDriver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-inventory.dir/build.make CMakeFiles/gen-inventory.dir/src/InventoryGeneratorDriver.cpp.i
.PHONY : src/InventoryGeneratorDriver.cpp.i

src/InventoryGeneratorDriver.s: src/InventoryGeneratorDriver.cpp.s
.PHONY : src/InventoryGeneratorDriver.s

# target to generate assembly for a file
src/InventoryGeneratorDriver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-inventory.dir/build.make CMakeFiles/gen-inventory.dir/src/InventoryGeneratorDriver.cpp.s
.PHONY : src/InventoryGeneratorDriver.cpp.s

src/InventoryManager.o: src/InventoryManager.cpp.o
.PHONY : src/InventoryManager.o

# target to build an object file
src/InventoryManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/InventoryManager.cpp.o
.PHONY : src/InventoryManager.cpp.o

src/InventoryManager.i: src/InventoryManager.cpp.i
.PHONY : src/InventoryManager.i

# target to preprocess a source file
src/InventoryManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/InventoryManager.cpp.i
.PHONY : src/InventoryManager.cpp.i

src/InventoryManager.s: src/InventoryManager.cpp.s
.PHONY : src/InventoryManager.s

# target to generate assembly for a file
src/InventoryManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/InventoryManager.cpp.s
.PHONY : src/InventoryManager.cpp.s

src/Login.o: src/Login.cpp.o
.PHONY : src/Login.o

# target to build an object file
src/Login.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Login.cpp.o
.PHONY : src/Login.cpp.o

src/Login.i: src/Login.cpp.i
.PHONY : src/Login.i

# target to preprocess a source file
src/Login.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Login.cpp.i
.PHONY : src/Login.cpp.i

src/Login.s: src/Login.cpp.s
.PHONY : src/Login.s

# target to generate assembly for a file
src/Login.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Login.cpp.s
.PHONY : src/Login.cpp.s

src/Sales.o: src/Sales.cpp.o
.PHONY : src/Sales.o

# target to build an object file
src/Sales.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Sales.cpp.o
.PHONY : src/Sales.cpp.o

src/Sales.i: src/Sales.cpp.i
.PHONY : src/Sales.i

# target to preprocess a source file
src/Sales.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Sales.cpp.i
.PHONY : src/Sales.cpp.i

src/Sales.s: src/Sales.cpp.s
.PHONY : src/Sales.s

# target to generate assembly for a file
src/Sales.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Sales.cpp.s
.PHONY : src/Sales.cpp.s

src/SalesGenerator.o: src/SalesGenerator.cpp.o
.PHONY : src/SalesGenerator.o

# target to build an object file
src/SalesGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-sales.dir/build.make CMakeFiles/gen-sales.dir/src/SalesGenerator.cpp.o
.PHONY : src/SalesGenerator.cpp.o

src/SalesGenerator.i: src/SalesGenerator.cpp.i
.PHONY : src/SalesGenerator.i

# target to preprocess a source file
src/SalesGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-sales.dir/build.make CMakeFiles/gen-sales.dir/src/SalesGenerator.cpp.i
.PHONY : src/SalesGenerator.cpp.i

src/SalesGenerator.s: src/SalesGenerator.cpp.s
.PHONY : src/SalesGenerator.s

# target to generate assembly for a file
src/SalesGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-sales.dir/build.make CMakeFiles/gen-sales.dir/src/SalesGenerator.cpp.s
.PHONY : src/SalesGenerator.cpp.s

src/SalesGeneratorDriver.o: src/SalesGeneratorDriver.cpp.o
.PHONY : src/SalesGeneratorDriver.o

# target to build an object file
src/SalesGeneratorDriver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-sales.dir/build.make CMakeFiles/gen-sales.dir/src/SalesGeneratorDriver.cpp.o
.PHONY : src/SalesGeneratorDriver.cpp.o

src/SalesGeneratorDriver.i: src/SalesGeneratorDriver.cpp.i
.PHONY : src/SalesGeneratorDriver.i

# target to preprocess a source file
src/SalesGeneratorDriver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-sales.dir/build.make CMakeFiles/gen-sales.dir/src/SalesGeneratorDriver.cpp.i
.PHONY : src/SalesGeneratorDriver.cpp.i

src/SalesGeneratorDriver.s: src/SalesGeneratorDriver.cpp.s
.PHONY : src/SalesGeneratorDriver.s

# target to generate assembly for a file
src/SalesGeneratorDriver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen-sales.dir/build.make CMakeFiles/gen-sales.dir/src/SalesGeneratorDriver.cpp.s
.PHONY : src/SalesGeneratorDriver.cpp.s

src/User.o: src/User.cpp.o
.PHONY : src/User.o

# target to build an object file
src/User.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/User.cpp.o
.PHONY : src/User.cpp.o

src/User.i: src/User.cpp.i
.PHONY : src/User.i

# target to preprocess a source file
src/User.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/User.cpp.i
.PHONY : src/User.cpp.i

src/User.s: src/User.cpp.s
.PHONY : src/User.s

# target to generate assembly for a file
src/User.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/User.cpp.s
.PHONY : src/User.cpp.s

src/loginscreen.o: src/loginscreen.cpp.o
.PHONY : src/loginscreen.o

# target to build an object file
src/loginscreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/loginscreen.cpp.o
.PHONY : src/loginscreen.cpp.o

src/loginscreen.i: src/loginscreen.cpp.i
.PHONY : src/loginscreen.i

# target to preprocess a source file
src/loginscreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/loginscreen.cpp.i
.PHONY : src/loginscreen.cpp.i

src/loginscreen.s: src/loginscreen.cpp.s
.PHONY : src/loginscreen.s

# target to generate assembly for a file
src/loginscreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/loginscreen.cpp.s
.PHONY : src/loginscreen.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gen-inventory_autogen"
	@echo "... gen-sales_autogen"
	@echo "... main_autogen"
	@echo "... gen-inventory"
	@echo "... gen-sales"
	@echo "... main"
	@echo "... gen-inventory_autogen/mocs_compilation.o"
	@echo "... gen-inventory_autogen/mocs_compilation.i"
	@echo "... gen-inventory_autogen/mocs_compilation.s"
	@echo "... gen-sales_autogen/mocs_compilation.o"
	@echo "... gen-sales_autogen/mocs_compilation.i"
	@echo "... gen-sales_autogen/mocs_compilation.s"
	@echo "... main_autogen/mocs_compilation.o"
	@echo "... main_autogen/mocs_compilation.i"
	@echo "... main_autogen/mocs_compilation.s"
	@echo "... src/ActiveInventory.o"
	@echo "... src/ActiveInventory.i"
	@echo "... src/ActiveInventory.s"
	@echo "... src/CSVEntry.o"
	@echo "... src/CSVEntry.i"
	@echo "... src/CSVEntry.s"
	@echo "... src/Date.o"
	@echo "... src/Date.i"
	@echo "... src/Date.s"
	@echo "... src/HelperFunctions.o"
	@echo "... src/HelperFunctions.i"
	@echo "... src/HelperFunctions.s"
	@echo "... src/InventoryGenerator.o"
	@echo "... src/InventoryGenerator.i"
	@echo "... src/InventoryGenerator.s"
	@echo "... src/InventoryGeneratorDriver.o"
	@echo "... src/InventoryGeneratorDriver.i"
	@echo "... src/InventoryGeneratorDriver.s"
	@echo "... src/InventoryManager.o"
	@echo "... src/InventoryManager.i"
	@echo "... src/InventoryManager.s"
	@echo "... src/Login.o"
	@echo "... src/Login.i"
	@echo "... src/Login.s"
	@echo "... src/Sales.o"
	@echo "... src/Sales.i"
	@echo "... src/Sales.s"
	@echo "... src/SalesGenerator.o"
	@echo "... src/SalesGenerator.i"
	@echo "... src/SalesGenerator.s"
	@echo "... src/SalesGeneratorDriver.o"
	@echo "... src/SalesGeneratorDriver.i"
	@echo "... src/SalesGeneratorDriver.s"
	@echo "... src/User.o"
	@echo "... src/User.i"
	@echo "... src/User.s"
	@echo "... src/loginscreen.o"
	@echo "... src/loginscreen.i"
	@echo "... src/loginscreen.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

