name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: load gtest
      run: |
        sudo apt-get install libgtest-dev
        sudo apt-get install cmake
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp lib/libgtest* /usr/lib

    - name: make
      run: make all

    - name: Run Unit Tests
      run: ./bin/unit_tests